package capa.igu.ventanas;

import capa.datos.elementos.Reunion;
import capa.datos.elementos.Usuario;
import capa.datos.modelos.ModeloListaString;
import capa.datos.modelos.ModeloListaUsuario;
import capa.igu.CapaIGU;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Ramón Francisco González Castillo
 */
public class VentanaGestionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConvocarReunion
     */
    public VentanaGestionAdmin() {
        initComponents();
        prepararCierreVentana();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorTipo = new javax.swing.ButtonGroup();
        jLabelGESINCAT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        btnAddUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textoSql = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaSindicatos = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        btnSindicato = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaDocumentos = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        btnAddDocumento = new javax.swing.JButton();
        btnSql = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnEliminarSindicato = new javax.swing.JButton();
        btnEliminarDocumento = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnAddReunion = new javax.swing.JButton();
        btnEliminarReunion = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaReunion = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        btnAddTipoUsuario = new javax.swing.JButton();
        btnEliminarTipoUsuario = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaTipoUsuario = new javax.swing.JList<>();
        btnAddTipoEmpresa = new javax.swing.JButton();
        btnEliminarTipoEmpresa = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaTipoEmpresa = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGESINCAT.setText("GESINCAT");

        jLabel1.setText("Administrador");

        jLabel2.setText("Usuarios");

        listaUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaUsuarios);

        btnAddUsuario.setText("Añadir usuario");
        btnAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Ejecutar SQL");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        listaSindicatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaSindicatos);

        jLabel9.setText("Sindicatos");

        btnSindicato.setText("Añadir sindicato");
        btnSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSindicatoActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        listaDocumentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaDocumentos);

        jLabel13.setText("Tipos de documento");

        btnAddDocumento.setText("Añadir tipo doc");
        btnAddDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocumentoActionPerformed(evt);
            }
        });

        btnSql.setText("Ejecutar SQL");
        btnSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqlActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setText("Eliminar usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        btnEliminarSindicato.setText("Eliminar sindicato");
        btnEliminarSindicato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSindicatoActionPerformed(evt);
            }
        });

        btnEliminarDocumento.setText("Eliminar documento");
        btnEliminarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDocumentoActionPerformed(evt);
            }
        });

        jLabel14.setText("Tipos de reunión");

        btnAddReunion.setText("Añadir tipo reunion");
        btnAddReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReunionActionPerformed(evt);
            }
        });

        btnEliminarReunion.setText("Eliminar reunion");
        btnEliminarReunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReunionActionPerformed(evt);
            }
        });

        listaReunion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaReunion);

        jLabel15.setText("Tipos de usuario sindicato");

        btnAddTipoUsuario.setText("Añadir tipo usuario");
        btnAddTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTipoUsuarioActionPerformed(evt);
            }
        });

        btnEliminarTipoUsuario.setText("Eliminar tipo usuario");
        btnEliminarTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoUsuarioActionPerformed(evt);
            }
        });

        listaTipoUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(listaTipoUsuario);

        btnAddTipoEmpresa.setText("Añadir tipo empresa");
        btnAddTipoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTipoEmpresaActionPerformed(evt);
            }
        });

        btnEliminarTipoEmpresa.setText("Eliminar tipo empresa");
        btnEliminarTipoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoEmpresaActionPerformed(evt);
            }
        });

        listaTipoEmpresa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(listaTipoEmpresa);

        jLabel16.setText("Tipos de usuario empresa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGESINCAT)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarReunion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddReunion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarSindicato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSindicato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2)
                    .addComponent(btnSql)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(textoSql))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarTipoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddTipoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel15))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGESINCAT)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSindicato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarSindicato))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarDocumento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddReunion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarReunion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarTipoUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTipoEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarTipoEmpresa)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textoSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btnSql)
                .addGap(3, 3, 3)
                .addComponent(btnMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        VentanaMenuPrincipal.get(CapaIGU.get()).setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        preguntarLogoutYOCerrar();
    }//GEN-LAST:event_jButton4ActionPerformed


    private void btnAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsuarioActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Introduzca el nombre de usuario");
        String pass = JOptionPane.showInputDialog(this, "Introduzca la clave de usuario");

        CapaIGU.get().executeSesion("INSERT INTO Usuarios VALUES (0,'" + pass + "' , '" + nombre + "')");
        setVisible(true);
    }//GEN-LAST:event_btnAddUsuarioActionPerformed

    private void btnSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSindicatoActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Introduzca el nombre del sindicato");
        CapaIGU.get().executeSesion("INSERT INTO Sindicatos VALUES (0 , '" + nombre + "')");
        setVisible(true);
    }//GEN-LAST:event_btnSindicatoActionPerformed

    private void btnAddDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocumentoActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Introduzca el tipo de documento");
        CapaIGU.get().executeSesion("INSERT INTO TiposDocumento VALUES (0 , '" + nombre + "')");
        setVisible(true);
    }//GEN-LAST:event_btnAddDocumentoActionPerformed

    private void btnSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqlActionPerformed
if(!textoSql.getText().equalsIgnoreCase(""))
    try {
        CapaIGU.get().execute(textoSql.getText());
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "SQL no interpretable \n"+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnSqlActionPerformed

    private void btnAddReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReunionActionPerformed
                String nombre = JOptionPane.showInputDialog(this, "Introduzca el tipo de reunión");
        CapaIGU.get().executeSesion("INSERT INTO TiposReunion VALUES (0 , '" + nombre + "')");
        setVisible(true);
    }//GEN-LAST:event_btnAddReunionActionPerformed

    private void btnAddTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTipoUsuarioActionPerformed
            String nombre = JOptionPane.showInputDialog(this, "Introduzca el tipo de usuario");
        CapaIGU.get().executeSesion("INSERT INTO TiposUsuario VALUES (0 , '" + nombre + "')");
        setVisible(true);
    }//GEN-LAST:event_btnAddTipoUsuarioActionPerformed

    private void btnAddTipoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTipoEmpresaActionPerformed
               String nombre = JOptionPane.showInputDialog(this, "Introduzca el tipo de usuario de empresa");
        CapaIGU.get().executeSesion("INSERT INTO TiposEmpresa VALUES (0 , '" + nombre + "')");
        setVisible(true);
    }//GEN-LAST:event_btnAddTipoEmpresaActionPerformed

    private void btnEliminarTipoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoEmpresaActionPerformed
            if (listaTipoEmpresa.getSelectedIndex() != -1) {
            String nombre = listaTipoEmpresa.getSelectedValue();
            CapaIGU.get().executeSesion("DELETE FROM TiposEmpresa WHERE Nombre= '" + nombre + "'");
            setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarTipoEmpresaActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        if (listaUsuarios.getSelectedIndex() != -1) {
            String nombre = listaUsuarios.getSelectedValue();
            CapaIGU.get().executeSesion("DELETE FROM Usuarios WHERE Nombre= '" + nombre + "'");
            setVisible(true);
        }

    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnEliminarSindicatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSindicatoActionPerformed
                if (listaSindicatos.getSelectedIndex() != -1) {
            String nombre = listaSindicatos.getSelectedValue();
            CapaIGU.get().executeSesion("DELETE FROM Sindicatos WHERE Nombre= '" + nombre + "'");
            setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarSindicatoActionPerformed

    private void btnEliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocumentoActionPerformed
              if (listaDocumentos.getSelectedIndex() != -1) {
            String nombre = listaDocumentos.getSelectedValue();
            CapaIGU.get().executeSesion("DELETE FROM TiposDocumento WHERE Nombre= '" + nombre + "'");
            setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarDocumentoActionPerformed

    private void btnEliminarReunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReunionActionPerformed
               if (listaReunion.getSelectedIndex() != -1) {
            String nombre = listaReunion.getSelectedValue();
            CapaIGU.get().executeSesion("DELETE FROM TiposReunion WHERE Nombre= '" + nombre + "'");
            setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarReunionActionPerformed

    private void btnEliminarTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoUsuarioActionPerformed
                if (listaTipoUsuario.getSelectedIndex() != -1) {
            String nombre = listaTipoUsuario.getSelectedValue();
            CapaIGU.get().executeSesion("DELETE FROM TiposUsuario WHERE Nombre= '" + nombre + "'");
            setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarTipoUsuarioActionPerformed

    private void errorSeleccion() {
        JOptionPane.showMessageDialog(null, "Debe seleccionar un solo elemento", "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void preguntarLogoutYOCerrar() {
        boolean si = DialogoConfirmar.preguntarLogout(this);
        if (si) {
            System.exit(0);
        }
    }

    private void prepararCierreVentana() {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                preguntarLogoutYOCerrar();
            }
        });
    }

    private void iniciarListas() {
        CapaIGU datos = CapaIGU.get();

        listaUsuarios.setModel(new ModeloListaString(datos.getUsuarios()));
        listaSindicatos.setModel(new ModeloListaString(datos.sindicatos()));
        listaDocumentos.setModel(new ModeloListaString(datos.getTiposDoc()));
        listaReunion.setModel(new ModeloListaString(datos.getTiposReunion()));
        listaTipoUsuario.setModel(new ModeloListaString(datos.getTiposUsuarios()));
        listaTipoEmpresa.setModel(new ModeloListaString(datos.getTiposEmpresa()));
    }

    @Override
    public void setVisible(boolean estado) {
        super.setVisible(estado);
        iniciarListas();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDocumento;
    private javax.swing.JButton btnAddReunion;
    private javax.swing.JButton btnAddTipoEmpresa;
    private javax.swing.JButton btnAddTipoUsuario;
    private javax.swing.JButton btnAddUsuario;
    private javax.swing.JButton btnEliminarDocumento;
    private javax.swing.JButton btnEliminarReunion;
    private javax.swing.JButton btnEliminarSindicato;
    private javax.swing.JButton btnEliminarTipoEmpresa;
    private javax.swing.JButton btnEliminarTipoUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSindicato;
    private javax.swing.JButton btnSql;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGESINCAT;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<String> listaDocumentos;
    private javax.swing.JList<String> listaReunion;
    private javax.swing.JList<String> listaSindicatos;
    private javax.swing.JList<String> listaTipoEmpresa;
    private javax.swing.JList<String> listaTipoUsuario;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.ButtonGroup selectorTipo;
    private javax.swing.JTextField textoSql;
    // End of variables declaration//GEN-END:variables
}
