
package capa.igu.ventanas;

import capa.datos.Rutas;
import capa.igu.CapaIGU;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramón Francisco González Castillo
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {
    
    private static VentanaMenuPrincipal instancia;
    private CapaIGU interfazDatos;//?nombre

    /**
     * Creates new form VentanaPrincipalAdmin
     */
    private VentanaMenuPrincipal(CapaIGU interfaz) {
        initComponents();
        prepararCierreVentana();
         this.interfazDatos= interfaz;
         jLabelAyunt.setText(Rutas.ayuntamiento());
    }
    
   public static VentanaMenuPrincipal get () {
        if (instancia == null) {
            JOptionPane.showMessageDialog(null,"Base de datos no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return instancia;
    }
    
    public static VentanaMenuPrincipal get (CapaIGU interfaz) {
        if (instancia == null) {
            instancia = new VentanaMenuPrincipal( interfaz);
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGSINCAT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonGesUsus = new javax.swing.JButton();
        jButtonGesReuniones = new javax.swing.JButton();
        jButtonGesDocs = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonGesOrgs = new javax.swing.JButton();
        jLabelAyunt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelGSINCAT.setText("GESINCAT");

        jLabel1.setText("Menú principal");

        jLabel2.setText("Ayuntamiento de");

        jButtonGesUsus.setText("Gestión usuarios");
        jButtonGesUsus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesUsusActionPerformed(evt);
            }
        });

        jButtonGesReuniones.setText("Gestión reuniones");
        jButtonGesReuniones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesReunionesActionPerformed(evt);
            }
        });

        jButtonGesDocs.setText("Gestión documentos");
        jButtonGesDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesDocsActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonGesOrgs.setText("Gestión organismos");
        jButtonGesOrgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesOrgsActionPerformed(evt);
            }
        });

        jLabelAyunt.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGSINCAT)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAyunt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGesOrgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGesUsus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGesReuniones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGesDocs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGSINCAT)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jLabelAyunt))
                .addGap(50, 50, 50)
                .addComponent(jButtonGesUsus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonGesOrgs)
                .addGap(28, 28, 28)
                .addComponent(jButtonGesReuniones)
                .addGap(28, 28, 28)
                .addComponent(jButtonGesDocs)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGesUsusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesUsusActionPerformed
        this.setVisible(false);
        new VentanaListaUsuarios(interfazDatos).setVisible(true);
    }//GEN-LAST:event_jButtonGesUsusActionPerformed

    private void jButtonGesOrgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesOrgsActionPerformed
        this.setVisible(false);
      new VentanaListaOrganismos(this).setVisible(true);
    }//GEN-LAST:event_jButtonGesOrgsActionPerformed

    private void jButtonGesReunionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesReunionesActionPerformed
       this.setVisible(false);
        new VentanaListaReuniones(interfazDatos).setVisible(true);
    }//GEN-LAST:event_jButtonGesReunionesActionPerformed

    private void jButtonGesDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesDocsActionPerformed
        this.setVisible(false);
        new VentanaListaDocumentosGenerales(this).setVisible(true);
    }//GEN-LAST:event_jButtonGesDocsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        preguntarLogoutYOCerrar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void preguntarLogoutYOCerrar () {
        boolean si = DialogoConfirmar.preguntarLogout(this);
        if (si) {
            System.exit(0);
        }        
    }
    
    private void prepararCierreVentana () {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent we) {
                preguntarLogoutYOCerrar();
            }
        });
    }
    
    public void cambiarEtiqAyunt (String s) {
        jLabelAyunt.setText(s);
        pack();
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGesDocs;
    private javax.swing.JButton jButtonGesOrgs;
    private javax.swing.JButton jButtonGesReuniones;
    private javax.swing.JButton jButtonGesUsus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAyunt;
    private javax.swing.JLabel jLabelGSINCAT;
    // End of variables declaration//GEN-END:variables
}
