
package capa.igu.ventanas;

import capa.datos.Rutas;
import capa.datos.elementos.Usuario;
import capa.datos.modelos.ModeloTablaUsuario;
import capa.igu.CapaIGU;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.html.simpleparser.HTMLWorker;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBoxBase;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramón Francisco González Castillo
 */
public class VentanaListaOrganismos extends javax.swing.JFrame {
JFrame padre;
ArrayList<Usuario> listaJuntaPersonal;
ArrayList<Usuario> listaComiteEmpresa;
    /**
     * Creates new form VentanaListaUsuarios
     */
    public VentanaListaOrganismos(JFrame padre) {
        initComponents();
        this.padre= padre;
        listaJuntaPersonal = CapaIGU.get().buscarUsuarios("Junta", null);
        listaComiteEmpresa= CapaIGU.get().buscarUsuarios("Comite", null);
        iniciarTabla();
        prepararCierreVentana();
    }
    private void iniciarTabla () {
        
        CapaIGU interfaz = CapaIGU.get();
        
        jTable1.setModel(new ModeloTablaUsuario(listaJuntaPersonal));
        jTable2.setModel(new ModeloTablaUsuario(listaComiteEmpresa));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnUsuarioJunta = new javax.swing.JButton();
        btnQuitarJunta = new javax.swing.JButton();
        btnAddComite = new javax.swing.JButton();
        btnQuitarComite = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIF/NIE", "Apellido1", "Apellido2", "Nombre", "Teléfono1", " WIDGETS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("GESINCAT");

        jLabel3.setText("Junta de Personal (personal funcionario)");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIF/NIE", "Apellido1", "Apellido2", "Nombre", "Teléfono1", " WIDGETS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Comité de Empresa (personal laboral)");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Atrás");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnUsuarioJunta.setText("Añadir usuario");
        btnUsuarioJunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioJuntaActionPerformed(evt);
            }
        });

        btnQuitarJunta.setText("Quitar usuario");
        btnQuitarJunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarJuntaActionPerformed(evt);
            }
        });

        btnAddComite.setText("Añadir usuario");
        btnAddComite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddComiteActionPerformed(evt);
            }
        });

        btnQuitarComite.setText("Quitar usuario");
        btnQuitarComite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarComiteActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir listado");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnImprimir)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddComite)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnQuitarJunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUsuarioJunta))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnQuitarComite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnUsuarioJunta)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarJunta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddComite)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarComite)
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(btnImprimir))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        for(Usuario usuario: listaJuntaPersonal)
            CapaIGU.get().vincular(usuario,-1);
         for(Usuario usuario: listaComiteEmpresa)
            CapaIGU.get().vincular(usuario,-2);
         
        this.setVisible(false);
        VentanaMenuPrincipal.get().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        preguntarLogoutYOCerrar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnUsuarioJuntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioJuntaActionPerformed
  new VentanaSeleccionUsuarios(this, listaJuntaPersonal,CapaIGU.get(), false).setVisible(true);
  this.setVisible(false);
        
    }//GEN-LAST:event_btnUsuarioJuntaActionPerformed

    private void btnQuitarJuntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarJuntaActionPerformed
              
        for(int i: jTable1.getSelectedRows())
          CapaIGU.get().desvincular(listaJuntaPersonal.get(i),-1);
    }//GEN-LAST:event_btnQuitarJuntaActionPerformed

    private void btnAddComiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddComiteActionPerformed
         new VentanaSeleccionUsuarios(this, listaComiteEmpresa,CapaIGU.get(), false).setVisible(true);
  this.setVisible(false);
    }//GEN-LAST:event_btnAddComiteActionPerformed

    private void btnQuitarComiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarComiteActionPerformed
               for(int i: jTable2.getSelectedRows())
          CapaIGU.get().desvincular(listaComiteEmpresa.get(i),-2);
    }//GEN-LAST:event_btnQuitarComiteActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
     try {
          
            BufferedReader br = new BufferedReader( new FileReader(new File("plantillas\\Organismos.html")));
            procesarPlantilla(br);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No existe la plantilla solicitada", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } 
        
    }//GEN-LAST:event_btnImprimirActionPerformed
    
    private void preguntarLogoutYOCerrar () {
        boolean si = DialogoConfirmar.preguntarLogout(this);
        if (si) {
            System.exit(0);
        }        
    }
    
    private void prepararCierreVentana () {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent we) {
                preguntarLogoutYOCerrar();
            }
        });
    }
    
    public void setVisible(boolean estado){
        super.setVisible(estado);
         iniciarTabla();
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComite;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnQuitarComite;
    private javax.swing.JButton btnQuitarJunta;
    private javax.swing.JButton btnUsuarioJunta;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void procesarPlantilla(BufferedReader br)  {
    try {
               
        
        Document document = new Document(PageSize.A4);
        PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(Rutas.rutaDocs()+Rutas.hoy()+"-Organismos"+".pdf"));
        document.open();
        document.addAuthor("Ayuntamiento de "+Rutas.ayuntamiento());
        document.addCreationDate();
        document.addTitle("Lista de participantes "+ Rutas.hoy());
        document.add(Rutas.cabecera());
        HTMLWorker htmlWorker = new HTMLWorker(document);
        
         StringBuilder cadena= new StringBuilder();
            String lectura = br.readLine();
            
            while(lectura!=null){
                lectura= lectura.replaceAll("#Fecha", Rutas.hoy());
                lectura= lectura.replaceAll("#miembrosJunta", usuarios("Junta"));
                 lectura= lectura.replaceAll("#miembrosEmpresa", usuarios("Comite"));
                 
                cadena.append(lectura);
               lectura = br.readLine();
               
            }
           
                
        htmlWorker.parse(new StringReader(cadena.toString()));
        document.close();
         File fichero = new File(Rutas.rutaDocs()+Rutas.hoy()+"-Organismos"+".pdf");
             Desktop.getDesktop().open(fichero);
    } catch (IOException | DocumentException ex) {
ex.printStackTrace();
    } 
 }
    
    private String usuarios(String tipo){
    ArrayList<Usuario> lista=    CapaIGU.get().buscarUsuarios(tipo, "");
    String aux ="<ul>";
    for(Usuario usuario: lista)
        aux = aux+"<li>"+usuario.getNombreCompleto()+"</li>";
    
    return aux+"</ul>";
    }
}
